// <auto-generated />
using System;
using HorariosIPBejaMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HorariosIPBejaMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241031214007_AddSolucaoHorarioTemp")]
    partial class AddSolucaoHorarioTemp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ALUNOUNIDADE_CURRICULAR", b =>
                {
                    b.Property<int>("aluno_id")
                        .HasColumnType("int");

                    b.Property<int>("uc_id")
                        .HasColumnType("int");

                    b.HasKey("aluno_id", "uc_id");

                    b.HasIndex("uc_id");

                    b.ToTable("ALUNOUNIDADE_CURRICULAR");
                });

            modelBuilder.Entity("DOCENTEPERIODO_HORARIO", b =>
                {
                    b.Property<int>("docente_id")
                        .HasColumnType("int");

                    b.Property<int>("periodo_horario_id")
                        .HasColumnType("int");

                    b.HasKey("docente_id", "periodo_horario_id");

                    b.ToTable("DOCENTEPERIODO_HORARIO");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.ALUNO", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int>("curso_id")
                        .HasColumnType("int");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__ALUNO__3213E83F2F31CEA8");

                    b.HasIndex("curso_id");

                    b.HasIndex(new[] { "numero" }, "UQ__ALUNO__FC77F211E4522784")
                        .IsUnique();

                    b.ToTable("ALUNO");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.ALUNO_UC", b =>
                {
                    b.Property<int>("aluno_id")
                        .HasColumnType("int")
                        .HasColumnName("aluno_id");

                    b.Property<int>("uc_id")
                        .HasColumnType("int")
                        .HasColumnName("uc_id");

                    b.HasKey("aluno_id", "uc_id")
                        .HasName("PK__ALUNO_UC__0378F9E125B17D91");

                    b.HasIndex("uc_id");

                    b.ToTable("ALUNO_UC", (string)null);
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.ANO_LETIVO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("data_fim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("data_inicio")
                        .HasColumnType("date");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PK__ANO_LETI__3213E83F565EF8AD");

                    b.HasIndex(new[] { "descricao" }, "UQ__ANO_LETI__91D38C2826011623")
                        .IsUnique();

                    b.ToTable("ANO_LETIVO");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.CALENDARIO_ACADEMICO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ano_letivo_id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("data")
                        .HasColumnType("date");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("semana_id")
                        .HasColumnType("int");

                    b.Property<string>("tipo_evento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PK__CALENDAR__3213E83F7DB74DB2");

                    b.HasIndex("ano_letivo_id");

                    b.HasIndex("semana_id");

                    b.HasIndex(new[] { "data" }, "UQ__CALENDAR__D9DE21E198D0C5EF")
                        .IsUnique();

                    b.ToTable("CALENDARIO_ACADEMICO");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.COORDENADOR_CURSO", b =>
                {
                    b.Property<int>("docente_id")
                        .HasColumnType("int");

                    b.Property<int>("curso_id")
                        .HasColumnType("int");

                    b.HasKey("docente_id")
                        .HasName("PK__COORDENA__32BA4B10A6FC47E8");

                    b.HasIndex("curso_id");

                    b.HasIndex(new[] { "docente_id" }, "UQ__COORDENA__32BA4B112EFE30D1")
                        .IsUnique();

                    b.ToTable("COORDENADOR_CURSO");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.CURSO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("escola_id")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("tipo_curso_id")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__CURSO__3213E83F1E85C08A");

                    b.HasIndex("escola_id");

                    b.HasIndex("tipo_curso_id");

                    b.HasIndex(new[] { "nome" }, "UQ__CURSO__6F71C0DCB838515A")
                        .IsUnique();

                    b.ToTable("CURSO");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.DOCENTE", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__DOCENTE__3213E83F28CAE0B0");

                    b.HasIndex(new[] { "numero" }, "UQ__DOCENTE__FC77F211B5C9725B")
                        .IsUnique();

                    b.ToTable("DOCENTE");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.ESCOLA", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("instituicao_id")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id")
                        .HasName("PK__ESCOLA__3213E83F731C77AB");

                    b.HasIndex("instituicao_id");

                    b.HasIndex(new[] { "nome" }, "UQ__ESCOLA__6F71C0DC3ED81842")
                        .IsUnique();

                    b.ToTable("ESCOLA");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.FUNCIONARIO", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("cargo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("instituicao_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_gabinete_gestao")
                        .HasColumnType("bit");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__FUNCIONA__3213E83F82D8CF83");

                    b.HasIndex("instituicao_id");

                    b.HasIndex(new[] { "numero" }, "UQ__FUNCIONA__FC77F211F97356F7")
                        .IsUnique();

                    b.ToTable("FUNCIONARIO");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.HORARIO_REFERENCIAL", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ano_letivo_id")
                        .HasColumnType("int");

                    b.Property<int>("docente_id")
                        .HasColumnType("int");

                    b.Property<int>("periodo_horario_id")
                        .HasColumnType("int");

                    b.Property<int>("sala_id")
                        .HasColumnType("int");

                    b.Property<int?>("solucaoHorarioId")
                        .HasColumnType("int");

                    b.Property<int>("turma_id")
                        .HasColumnType("int");

                    b.Property<int>("uc_id")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__HORARIO___3213E83FE45D08D7");

                    b.HasIndex("ano_letivo_id");

                    b.HasIndex("docente_id");

                    b.HasIndex("periodo_horario_id");

                    b.HasIndex("sala_id");

                    b.HasIndex("solucaoHorarioId");

                    b.HasIndex("turma_id");

                    b.HasIndex("uc_id");

                    b.ToTable("HORARIO_REFERENCIAL");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.HORARIO_SEMANAL", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ano_letivo_id")
                        .HasColumnType("int");

                    b.Property<int>("docente_id")
                        .HasColumnType("int");

                    b.Property<int>("periodo_horario_id")
                        .HasColumnType("int");

                    b.Property<int>("sala_id")
                        .HasColumnType("int");

                    b.Property<int>("semana_id")
                        .HasColumnType("int");

                    b.Property<int>("turma_id")
                        .HasColumnType("int");

                    b.Property<int>("uc_id")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__HORARIO___3213E83F9DDEF4CF");

                    b.HasIndex("ano_letivo_id");

                    b.HasIndex("docente_id");

                    b.HasIndex("periodo_horario_id");

                    b.HasIndex("sala_id");

                    b.HasIndex("semana_id");

                    b.HasIndex("turma_id");

                    b.HasIndex("uc_id");

                    b.ToTable("HORARIO_SEMANAL");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.INSTITUICAO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id")
                        .HasName("PK__INSTITUI__3213E83FF20C0F4B");

                    b.HasIndex(new[] { "nome" }, "UQ__INSTITUI__6F71C0DCA200F591")
                        .IsUnique();

                    b.ToTable("INSTITUICAO");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.PERIODO_HORARIO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("dia_semana")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<TimeOnly>("hora_fim")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("hora_inicio")
                        .HasColumnType("time");

                    b.HasKey("id")
                        .HasName("PK__PERIODO___3213E83F49C1BD39");

                    b.ToTable("PERIODO_HORARIO");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.SALA", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("capacidade")
                        .HasColumnType("int");

                    b.Property<int>("escola_id")
                        .HasColumnType("int");

                    b.Property<string>("localizacao")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("recursos_adicionais")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("id")
                        .HasName("PK__SALA__3213E83F13588E39");

                    b.HasIndex("escola_id");

                    b.HasIndex(new[] { "nome" }, "UQ__SALA__6F71C0DC9E272544")
                        .IsUnique();

                    b.ToTable("SALA");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.SEMANA", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ano_letivo_id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("data_fim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("data_inicio")
                        .HasColumnType("date");

                    b.Property<int>("numero_semana")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__SEMANAS__3213E83F93C51456");

                    b.HasIndex("ano_letivo_id");

                    b.ToTable("SEMANAS");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.SolucaoHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SOLUCAO_HORARIO");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.SolucaoHorarioTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DadosJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SolucaoHorarioTemps");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.TIPO_AULA", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PK__TIPO_AUL__3213E83FED8EF83C");

                    b.HasIndex(new[] { "descricao" }, "UQ__TIPO_AUL__91D38C28863316F7")
                        .IsUnique();

                    b.ToTable("TIPO_AULA");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.TIPO_CURSO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PK__TIPO_CUR__3213E83F8B557432");

                    b.HasIndex(new[] { "descricao" }, "UQ__TIPO_CUR__91D38C28ACBF61FC")
                        .IsUnique();

                    b.ToTable("TIPO_CURSO");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.TIPO_UTILIZADOR", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PK__TIPO_UTI__3213E83F24E0000D");

                    b.HasIndex(new[] { "descricao" }, "UQ__TIPO_UTI__91D38C28D3DEAB80")
                        .IsUnique();

                    b.ToTable("TIPO_UTILIZADOR");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.TURMA", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("docente_id")
                        .HasColumnType("int");

                    b.Property<int>("duracao")
                        .HasColumnType("int");

                    b.Property<int>("tipo_aula_id")
                        .HasColumnType("int");

                    b.Property<string>("turma_label")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("unidade_curricular_id")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__TURMA__3213E83FA0C01996");

                    b.HasIndex("docente_id");

                    b.HasIndex("tipo_aula_id");

                    b.HasIndex("unidade_curricular_id");

                    b.ToTable("TURMA");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.UC_DOCENTE", b =>
                {
                    b.Property<int>("uc_id")
                        .HasColumnType("int");

                    b.Property<int>("docente_id")
                        .HasColumnType("int");

                    b.Property<int>("tipo_aula_id")
                        .HasColumnType("int");

                    b.HasKey("uc_id", "docente_id", "tipo_aula_id")
                        .HasName("PK__UC_DOCEN__ACC3C4154869A555");

                    b.HasIndex("docente_id");

                    b.HasIndex("tipo_aula_id");

                    b.ToTable("UC_DOCENTE");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.UNIDADE_CURRICULAR", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("carga_horaria_pratica")
                        .HasColumnType("int");

                    b.Property<int>("carga_horaria_teorica")
                        .HasColumnType("int");

                    b.Property<int>("curso_id")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("numero_turmas_praticas")
                        .HasColumnType("int");

                    b.Property<int>("numero_turmas_teoricas")
                        .HasColumnType("int");

                    b.Property<int>("semestre")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__UNIDADE___3213E83FF42A1072");

                    b.HasIndex("curso_id");

                    b.HasIndex(new[] { "nome" }, "UQ__UNIDADE___6F71C0DCEDA3E211")
                        .IsUnique();

                    b.ToTable("UNIDADE_CURRICULAR");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.UTILIZADOR", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("senha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varbinary(64)");

                    b.HasKey("id")
                        .HasName("PK__UTILIZAD__3213E83F5AD3497F");

                    b.HasIndex(new[] { "email" }, "UQ__UTILIZAD__AB6E6164A5B09CFF")
                        .IsUnique();

                    b.ToTable("UTILIZADOR");
                });

            modelBuilder.Entity("INDISPONIBILIDADE_DOCENTE", b =>
                {
                    b.Property<int>("docente_id")
                        .HasColumnType("int");

                    b.Property<int>("periodo_horario_id")
                        .HasColumnType("int");

                    b.HasKey("docente_id", "periodo_horario_id")
                        .HasName("PK__INDISPON__7C4171043BA37F58");

                    b.HasIndex("periodo_horario_id");

                    b.ToTable("INDISPONIBILIDADE_DOCENTE", (string)null);
                });

            modelBuilder.Entity("INDISPONIBILIDADE_SALA", b =>
                {
                    b.Property<int>("sala_id")
                        .HasColumnType("int");

                    b.Property<int>("periodo_horario_id")
                        .HasColumnType("int");

                    b.HasKey("sala_id", "periodo_horario_id")
                        .HasName("PK__INDISPON__B48EB5D3DDA4769F");

                    b.HasIndex("periodo_horario_id");

                    b.ToTable("INDISPONIBILIDADE_SALA", (string)null);
                });

            modelBuilder.Entity("PERIODO_HORARIOSALA", b =>
                {
                    b.Property<int>("periodo_horario_id")
                        .HasColumnType("int");

                    b.Property<int>("sala_id")
                        .HasColumnType("int");

                    b.HasKey("periodo_horario_id", "sala_id");

                    b.ToTable("PERIODO_HORARIOSALA");
                });

            modelBuilder.Entity("SALAUNIDADE_CURRICULAR", b =>
                {
                    b.Property<int>("sala_id")
                        .HasColumnType("int");

                    b.Property<int>("unidade_curricular_id")
                        .HasColumnType("int");

                    b.HasKey("sala_id", "unidade_curricular_id");

                    b.ToTable("SALAUNIDADE_CURRICULAR");
                });

            modelBuilder.Entity("TIPO_UTILIZADORUTILIZADOR", b =>
                {
                    b.Property<int>("tipo_utilizador_id")
                        .HasColumnType("int");

                    b.Property<int>("utilizador_id")
                        .HasColumnType("int");

                    b.HasKey("tipo_utilizador_id", "utilizador_id");

                    b.ToTable("TIPO_UTILIZADORUTILIZADOR");
                });

            modelBuilder.Entity("UC_SALA", b =>
                {
                    b.Property<int>("unidade_curricular_id")
                        .HasColumnType("int");

                    b.Property<int>("sala_id")
                        .HasColumnType("int");

                    b.HasKey("unidade_curricular_id", "sala_id")
                        .HasName("PK__UC_SALA__6D7FA028C298D6E8");

                    b.HasIndex("sala_id");

                    b.ToTable("UC_SALA", (string)null);
                });

            modelBuilder.Entity("UTILIZADOR_TIPO_UTILIZADOR", b =>
                {
                    b.Property<int>("utilizador_id")
                        .HasColumnType("int");

                    b.Property<int>("tipo_utilizador_id")
                        .HasColumnType("int");

                    b.HasKey("utilizador_id", "tipo_utilizador_id")
                        .HasName("PK__UTILIZAD__765AED7DA60D76A1");

                    b.HasIndex("tipo_utilizador_id");

                    b.ToTable("UTILIZADOR_TIPO_UTILIZADOR", (string)null);
                });

            modelBuilder.Entity("ALUNOUNIDADE_CURRICULAR", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.ALUNO", null)
                        .WithMany()
                        .HasForeignKey("aluno_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorariosIPBejaMVC.Models.UNIDADE_CURRICULAR", null)
                        .WithMany()
                        .HasForeignKey("uc_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.ALUNO", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.CURSO", "curso")
                        .WithMany("ALUNOs")
                        .HasForeignKey("curso_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ALUNO__curso_id__66603565");

                    b.HasOne("HorariosIPBejaMVC.Models.UTILIZADOR", "idNavigation")
                        .WithOne("ALUNO")
                        .HasForeignKey("HorariosIPBejaMVC.Models.ALUNO", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ALUNO__id__656C112C");

                    b.Navigation("curso");

                    b.Navigation("idNavigation");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.ALUNO_UC", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.ALUNO", "ALUNO")
                        .WithMany("ALUNO_UCs")
                        .HasForeignKey("aluno_id")
                        .IsRequired()
                        .HasConstraintName("FK__ALUNO_UC__aluno___339FAB6E");

                    b.HasOne("HorariosIPBejaMVC.Models.UNIDADE_CURRICULAR", "UNIDADE_CURRICULAR")
                        .WithMany("ALUNO_UCs")
                        .HasForeignKey("uc_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ALUNO_UC__uc_id__3493CFA7");

                    b.Navigation("ALUNO");

                    b.Navigation("UNIDADE_CURRICULAR");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.CALENDARIO_ACADEMICO", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.ANO_LETIVO", "ano_letivo")
                        .WithMany("CALENDARIO_ACADEMICOs")
                        .HasForeignKey("ano_letivo_id")
                        .IsRequired()
                        .HasConstraintName("FK__CALENDARI__ano_l__0F624AF8");

                    b.HasOne("HorariosIPBejaMVC.Models.SEMANA", "semana")
                        .WithMany("CALENDARIO_ACADEMICOs")
                        .HasForeignKey("semana_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__CALENDARI__seman__10566F31");

                    b.Navigation("ano_letivo");

                    b.Navigation("semana");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.COORDENADOR_CURSO", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.CURSO", "curso")
                        .WithMany("COORDENADOR_CURSOs")
                        .HasForeignKey("curso_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__COORDENAD__curso__2CF2ADDF");

                    b.HasOne("HorariosIPBejaMVC.Models.DOCENTE", "docente")
                        .WithOne("COORDENADOR_CURSO")
                        .HasForeignKey("HorariosIPBejaMVC.Models.COORDENADOR_CURSO", "docente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__COORDENAD__docen__2BFE89A6");

                    b.Navigation("curso");

                    b.Navigation("docente");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.CURSO", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.ESCOLA", "escola")
                        .WithMany("CURSOs")
                        .HasForeignKey("escola_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CURSO__escola_id__619B8048");

                    b.HasOne("HorariosIPBejaMVC.Models.TIPO_CURSO", "tipo_curso")
                        .WithMany("CURSOs")
                        .HasForeignKey("tipo_curso_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CURSO__tipo_curs__60A75C0F");

                    b.Navigation("escola");

                    b.Navigation("tipo_curso");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.DOCENTE", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.UTILIZADOR", "idNavigation")
                        .WithOne("DOCENTE")
                        .HasForeignKey("HorariosIPBejaMVC.Models.DOCENTE", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DOCENTE__id__5CD6CB2B");

                    b.Navigation("idNavigation");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.ESCOLA", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.INSTITUICAO", "instituicao")
                        .WithMany("ESCOLAs")
                        .HasForeignKey("instituicao_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ESCOLA_INSTITUICAO");

                    b.Navigation("instituicao");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.FUNCIONARIO", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.UTILIZADOR", "idNavigation")
                        .WithOne("FUNCIONARIO")
                        .HasForeignKey("HorariosIPBejaMVC.Models.FUNCIONARIO", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FUNCIONARIO__id__7EF6D905");

                    b.HasOne("HorariosIPBejaMVC.Models.INSTITUICAO", "instituicao")
                        .WithMany("FUNCIONARIOs")
                        .HasForeignKey("instituicao_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FUNCIONAR__insti__7FEAFD3E");

                    b.Navigation("idNavigation");

                    b.Navigation("instituicao");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.HORARIO_REFERENCIAL", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.ANO_LETIVO", "ano_letivo")
                        .WithMany("HORARIO_REFERENCIALs")
                        .HasForeignKey("ano_letivo_id")
                        .IsRequired()
                        .HasConstraintName("FK__HORARIO_R__ano_l__17F790F9");

                    b.HasOne("HorariosIPBejaMVC.Models.DOCENTE", "docente")
                        .WithMany("HORARIO_REFERENCIALs")
                        .HasForeignKey("docente_id")
                        .IsRequired()
                        .HasConstraintName("FK__HORARIO_R__docen__151B244E");

                    b.HasOne("HorariosIPBejaMVC.Models.PERIODO_HORARIO", "periodo_horario")
                        .WithMany("HORARIO_REFERENCIALs")
                        .HasForeignKey("periodo_horario_id")
                        .IsRequired()
                        .HasConstraintName("FK__HORARIO_R__perio__17036CC0");

                    b.HasOne("HorariosIPBejaMVC.Models.SALA", "sala")
                        .WithMany("HORARIO_REFERENCIALs")
                        .HasForeignKey("sala_id")
                        .IsRequired()
                        .HasConstraintName("FK__HORARIO_R__sala___160F4887");

                    b.HasOne("HorariosIPBejaMVC.Models.SolucaoHorario", "SolucaoHorario")
                        .WithMany("HorariosReferenciais")
                        .HasForeignKey("solucaoHorarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HorariosIPBejaMVC.Models.TURMA", "turma")
                        .WithMany("HORARIO_REFERENCIALs")
                        .HasForeignKey("turma_id")
                        .IsRequired()
                        .HasConstraintName("FK__HORARIO_R__turma__14270015");

                    b.HasOne("HorariosIPBejaMVC.Models.UNIDADE_CURRICULAR", "uc")
                        .WithMany("HORARIO_REFERENCIALs")
                        .HasForeignKey("uc_id")
                        .IsRequired()
                        .HasConstraintName("FK__HORARIO_R__uc_id__1332DBDC");

                    b.Navigation("SolucaoHorario");

                    b.Navigation("ano_letivo");

                    b.Navigation("docente");

                    b.Navigation("periodo_horario");

                    b.Navigation("sala");

                    b.Navigation("turma");

                    b.Navigation("uc");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.HORARIO_SEMANAL", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.ANO_LETIVO", "ano_letivo")
                        .WithMany("HORARIO_SEMANALs")
                        .HasForeignKey("ano_letivo_id")
                        .IsRequired()
                        .HasConstraintName("FK__HORARIO_S__ano_l__208CD6FA");

                    b.HasOne("HorariosIPBejaMVC.Models.DOCENTE", "docente")
                        .WithMany("HORARIO_SEMANALs")
                        .HasForeignKey("docente_id")
                        .IsRequired()
                        .HasConstraintName("FK__HORARIO_S__docen__1CBC4616");

                    b.HasOne("HorariosIPBejaMVC.Models.PERIODO_HORARIO", "periodo_horario")
                        .WithMany("HORARIO_SEMANALs")
                        .HasForeignKey("periodo_horario_id")
                        .IsRequired()
                        .HasConstraintName("FK__HORARIO_S__perio__1EA48E88");

                    b.HasOne("HorariosIPBejaMVC.Models.SALA", "sala")
                        .WithMany("HORARIO_SEMANALs")
                        .HasForeignKey("sala_id")
                        .IsRequired()
                        .HasConstraintName("FK__HORARIO_S__sala___1DB06A4F");

                    b.HasOne("HorariosIPBejaMVC.Models.SEMANA", "semana")
                        .WithMany("HORARIO_SEMANALs")
                        .HasForeignKey("semana_id")
                        .IsRequired()
                        .HasConstraintName("FK__HORARIO_S__seman__1F98B2C1");

                    b.HasOne("HorariosIPBejaMVC.Models.TURMA", "turma")
                        .WithMany("HORARIO_SEMANALs")
                        .HasForeignKey("turma_id")
                        .IsRequired()
                        .HasConstraintName("FK__HORARIO_S__turma__1BC821DD");

                    b.HasOne("HorariosIPBejaMVC.Models.UNIDADE_CURRICULAR", "uc")
                        .WithMany("HORARIO_SEMANALs")
                        .HasForeignKey("uc_id")
                        .IsRequired()
                        .HasConstraintName("FK__HORARIO_S__uc_id__1AD3FDA4");

                    b.Navigation("ano_letivo");

                    b.Navigation("docente");

                    b.Navigation("periodo_horario");

                    b.Navigation("sala");

                    b.Navigation("semana");

                    b.Navigation("turma");

                    b.Navigation("uc");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.SALA", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.ESCOLA", "escola")
                        .WithMany("SALAs")
                        .HasForeignKey("escola_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SALA__escola_id__6B24EA82");

                    b.Navigation("escola");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.SEMANA", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.ANO_LETIVO", "ano_letivo")
                        .WithMany("SEMANAs")
                        .HasForeignKey("ano_letivo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SEMANAS__ano_let__0A9D95DB");

                    b.Navigation("ano_letivo");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.TURMA", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.DOCENTE", "docente")
                        .WithMany("TURMAs")
                        .HasForeignKey("docente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TURMA__docente_i__76969D2E");

                    b.HasOne("HorariosIPBejaMVC.Models.TIPO_AULA", "tipo_aula")
                        .WithMany("TURMAs")
                        .HasForeignKey("tipo_aula_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TURMA__tipo_aula__778AC167");

                    b.HasOne("HorariosIPBejaMVC.Models.UNIDADE_CURRICULAR", "unidade_curricular")
                        .WithMany("TURMAs")
                        .HasForeignKey("unidade_curricular_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TURMA__unidade_c__75A278F5");

                    b.Navigation("docente");

                    b.Navigation("tipo_aula");

                    b.Navigation("unidade_curricular");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.UC_DOCENTE", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.DOCENTE", "docente")
                        .WithMany("UC_DOCENTEs")
                        .HasForeignKey("docente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UC_DOCENT__docen__7B5B524B");

                    b.HasOne("HorariosIPBejaMVC.Models.TIPO_AULA", "tipo_aula")
                        .WithMany("UC_DOCENTEs")
                        .HasForeignKey("tipo_aula_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UC_DOCENT__tipo___7C4F7684");

                    b.HasOne("HorariosIPBejaMVC.Models.UNIDADE_CURRICULAR", "uc")
                        .WithMany("UC_DOCENTEs")
                        .HasForeignKey("uc_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UC_DOCENT__uc_id__7A672E12");

                    b.Navigation("docente");

                    b.Navigation("tipo_aula");

                    b.Navigation("uc");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.UNIDADE_CURRICULAR", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.CURSO", "curso")
                        .WithMany("UNIDADE_CURRICULARs")
                        .HasForeignKey("curso_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UNIDADE_C__curso__72C60C4A");

                    b.Navigation("curso");
                });

            modelBuilder.Entity("INDISPONIBILIDADE_DOCENTE", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.DOCENTE", null)
                        .WithMany()
                        .HasForeignKey("docente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__INDISPONI__docen__236943A5");

                    b.HasOne("HorariosIPBejaMVC.Models.PERIODO_HORARIO", null)
                        .WithMany()
                        .HasForeignKey("periodo_horario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__INDISPONI__perio__245D67DE");
                });

            modelBuilder.Entity("INDISPONIBILIDADE_SALA", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.PERIODO_HORARIO", null)
                        .WithMany()
                        .HasForeignKey("periodo_horario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__INDISPONI__perio__282DF8C2");

                    b.HasOne("HorariosIPBejaMVC.Models.SALA", null)
                        .WithMany()
                        .HasForeignKey("sala_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__INDISPONI__sala___2739D489");
                });

            modelBuilder.Entity("UC_SALA", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.SALA", null)
                        .WithMany()
                        .HasForeignKey("sala_id")
                        .IsRequired()
                        .HasConstraintName("FK__UC_SALA__sala_id__03F0984C");

                    b.HasOne("HorariosIPBejaMVC.Models.UNIDADE_CURRICULAR", null)
                        .WithMany()
                        .HasForeignKey("unidade_curricular_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UC_SALA__unidade__02FC7413");
                });

            modelBuilder.Entity("UTILIZADOR_TIPO_UTILIZADOR", b =>
                {
                    b.HasOne("HorariosIPBejaMVC.Models.TIPO_UTILIZADOR", null)
                        .WithMany()
                        .HasForeignKey("tipo_utilizador_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UTILIZADO__tipo___59063A47");

                    b.HasOne("HorariosIPBejaMVC.Models.UTILIZADOR", null)
                        .WithMany()
                        .HasForeignKey("utilizador_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UTILIZADO__utili__5812160E");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.ALUNO", b =>
                {
                    b.Navigation("ALUNO_UCs");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.ANO_LETIVO", b =>
                {
                    b.Navigation("CALENDARIO_ACADEMICOs");

                    b.Navigation("HORARIO_REFERENCIALs");

                    b.Navigation("HORARIO_SEMANALs");

                    b.Navigation("SEMANAs");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.CURSO", b =>
                {
                    b.Navigation("ALUNOs");

                    b.Navigation("COORDENADOR_CURSOs");

                    b.Navigation("UNIDADE_CURRICULARs");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.DOCENTE", b =>
                {
                    b.Navigation("COORDENADOR_CURSO");

                    b.Navigation("HORARIO_REFERENCIALs");

                    b.Navigation("HORARIO_SEMANALs");

                    b.Navigation("TURMAs");

                    b.Navigation("UC_DOCENTEs");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.ESCOLA", b =>
                {
                    b.Navigation("CURSOs");

                    b.Navigation("SALAs");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.INSTITUICAO", b =>
                {
                    b.Navigation("ESCOLAs");

                    b.Navigation("FUNCIONARIOs");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.PERIODO_HORARIO", b =>
                {
                    b.Navigation("HORARIO_REFERENCIALs");

                    b.Navigation("HORARIO_SEMANALs");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.SALA", b =>
                {
                    b.Navigation("HORARIO_REFERENCIALs");

                    b.Navigation("HORARIO_SEMANALs");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.SEMANA", b =>
                {
                    b.Navigation("CALENDARIO_ACADEMICOs");

                    b.Navigation("HORARIO_SEMANALs");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.SolucaoHorario", b =>
                {
                    b.Navigation("HorariosReferenciais");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.TIPO_AULA", b =>
                {
                    b.Navigation("TURMAs");

                    b.Navigation("UC_DOCENTEs");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.TIPO_CURSO", b =>
                {
                    b.Navigation("CURSOs");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.TURMA", b =>
                {
                    b.Navigation("HORARIO_REFERENCIALs");

                    b.Navigation("HORARIO_SEMANALs");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.UNIDADE_CURRICULAR", b =>
                {
                    b.Navigation("ALUNO_UCs");

                    b.Navigation("HORARIO_REFERENCIALs");

                    b.Navigation("HORARIO_SEMANALs");

                    b.Navigation("TURMAs");

                    b.Navigation("UC_DOCENTEs");
                });

            modelBuilder.Entity("HorariosIPBejaMVC.Models.UTILIZADOR", b =>
                {
                    b.Navigation("ALUNO");

                    b.Navigation("DOCENTE");

                    b.Navigation("FUNCIONARIO");
                });
#pragma warning restore 612, 618
        }
    }
}
